### ISSUE TITLE
Price chart is not loading 

### ISSUE THREAD

**Issue by BOR4** [Uniswap/v3-info#132]
**Bug Description**
![image](https://user-images.githubusercontent.com/40821065/131032704-111947ae-ab36-4ccc-9c46-e30e5f7b28b2.png)

It just buffers logo and never loads

![image](https://user-images.githubusercontent.com/40821065/131032812-dce336f3-85d8-4d21-b616-1392e4d79eb6.png)

I see bunch of these in network tab

Debugger tab looks clean
**Steps to Reproduce**

Just open any token

**Expected Behavior**
Price chart loads and shows ETH is $10k (at least)

**Additional Context**
![image](https://user-images.githubusercontent.com/40821065/131033030-a49bd082-5027-4b21-ac28-467db9ba49ef.png)
latest synced block is also missing ... can it be related?

**Comment by willhennessy** [comment]
working now!

**Comment by willhennessy** [comment]
working now!
