### ISSUE TITLE
Optimism & Arbitrum token lists fail to load

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/v3-info#202]
On info site, all images from the optimism and arbitrum token lists fail to load.  Looks like a validation error, probably related to the new L2 mapping extension field they both added.

```
Failed to get list at url https://static.optimism.io/optimism.tokenlist.json Error: Token list failed validation: .tokens[114].name should match pattern "^[ \w.'+\-%\/À-ÖØ-öø-ÿ:]+$"; .tokens[115].name should match pattern "^[ \w.'+\-%\/À-ÖØ-öø-ÿ:]+$"
    at main.bbd7a53f.chunk.js:1:224981
    at l (4.c91dcfe8.chunk.js:2:1796405)
    at Generator._invoke (4.c91dcfe8.chunk.js:2:1796193)
    at Generator.next (4.c91dcfe8.chunk.js:2:1796830)
    at n (4.c91dcfe8.chunk.js:2:165176)
    at s (4.c91dcfe8.chunk.js:2:165379)
```

**Comment by moodysalem** [comment]
moody@MacBook-Pro ~> curl https://static.optimism.io/optimism.tokenlist.json | jq '.tokens[114]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40433  100 40433    0     0   458k      0 --:--:-- --:--:-- --:--:--  493k
{
  "chainId": 1,
  "address": "0xa693b19d2931d498c5b318df961919bb4aee87a5",
  "name": "UST (Wormhole)",
  "symbol": "UST",
  "decimals": 6,
  "logoURI": "https://ethereum-optimism.github.io/logos/UST.png",
  "extensions": {
    "optimismBridgeAddress": "0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1"
  }
}
moody@MacBook-Pro ~> curl https://static.optimism.io/optimism.tokenlist.json | jq '.tokens[115]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40433  100 40433    0     0   560k      0 --:--:-- --:--:-- --:--:--  636k
{
  "chainId": 10,
  "address": "0xBA28feb4b6A6b81e3F26F08b83a19E715C4294fd",
  "name": "UST (Wormhole)",
  "symbol": "UST",
  "decimals": 6,
  "logoURI": "https://ethereum-optimism.github.io/logos/UST.png",
  "extensions": {
    "optimismBridgeAddress": "0x4200000000000000000000000000000000000010"
  }
}
